spring:
  application:
    name: template

telegram:
  token: 8194718253:AAGwC6VIXgl3LRcf0WmzwQbpU63iyWU1ar0
  webhook:
    url: https://noco.second-space.ru
    path: /webhook

logging:
  level:
    tech.dirwul.nocoshop: debug